import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.kalethra.app',
  appName: 'Kalethra',
  webDir: 'dist',
  ios: {
    // Health integration is Android-only for now (phase 6.2). Apple Health follows in its own
    // phase with entitlement and usage texts; until then the iOS app must not link HealthKit.
    // Haptics: the short vibration when the rest timer ends (phase 13).
    includePlugins: [
      '@capacitor-community/sqlite',
      '@capacitor/app',
      '@capacitor/barcode-scanner',
      '@capacitor/haptics',
    ],
  },
  plugins: {
    CapacitorSQLite: {
      iosDatabaseLocation: 'Library/CapacitorDatabase',
      // SQLCipher encryption; the key is generated by the app and kept by the plugin in the
      // iOS Keychain / Android Keystore-backed storage. See docs/PRIVACY.md.
      iosIsEncryption: true,
      iosKeychainPrefix: 'kalethra',
      androidIsEncryption: true,
    },
    SystemBars: {
      insetsHandling: 'css',
      initialViewportFitValueHint: 'cover',
    },
  },
};

export default config;
