import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.kalethra.app',
  appName: 'Kalethra',
  webDir: 'dist',
  plugins: {
    CapacitorSQLite: {
      iosDatabaseLocation: 'Library/CapacitorDatabase',
      // SQLCipher encryption; the key is generated by the app and kept by the plugin in the
      // iOS Keychain / Android Keystore-backed storage. See docs/PRIVACY.md.
      iosIsEncryption: true,
      iosKeychainPrefix: 'kalethra',
      androidIsEncryption: true,
    },
    SystemBars: {
      insetsHandling: 'css',
      initialViewportFitValueHint: 'cover',
    },
  },
};

export default config;
